Set requirements downstream deps (#2205)
* Set requirements downstream deps

A recent upgrade of some downstream dependency seems to have broken some Airflow product jobs, and is causing the following error when producing kafka messages:

  File "/var/www/airflow/airflow_venv/local/lib/python2.7/site-packages/kafka/protocol/types.py", line 93, in encode
    return Int32.encode(len(value)) + value
TypeError: object of type '_io.BytesIO' has no len()

After applying a diff between the previous release two weeks ago and the most recent release, I've identified all downstream changes. This commit fixes these changes to the version they were previously, in an attempt to fix the bug.

* Update requirements.txt